weather_wear/community/urls.py
from django.urls import path
from .views import *

app_name = "community"
urlpatterns = [
    path('', show, name="show"),
    path('<str:id>', detail, name="detail"),
    path('new/', new, name="new"),
    path('create/', create, name="create"),
    path('edit/<str:id>', edit, name="edit"),
    path('update/<str:id>', update, name="update"),
    path('delete/<str:id>', delete, name="delete"),
    path('<str:community_id>/create_comment', create_comment, name="create_comment"),
    path('<int:comment_id>/update_comment', update_comment, name="update_comment"),
    path('<int:comment_id>/delete_comment', delete_comment, name="delete_comment"),
    path('<int:community_id>/community_like', community_like, name="community_like"),
]

weather_wear/myPage/urls.py
from django.urls import path
from . import views

app_name = "myPage"
urlpatterns = [
    path('',views.mypage, name="mypage"),
    path('profile/', views.profile, name="profile"),
    path('edit/', views.edit_profile, name="edit"),
    path('update/', views.update_profile, name="update"),
    path('writing_list/', views.writing_list, name="writing_list"),
    path('filter_list/', views.filter_list, name="filter_list"),
    path('myclothes/', views.my_clothes, name='my_clothes'),
    path('newclothes/', views.new_clothes, name='new_clothes'),
    path('createclothes/',views.create_clothes, name='create_clothes'),
    path('<str:id>',views.detail_clothes, name="detail_clothes"),
    path('edit/<str:id>', views.edit_clothes, name='edit_clothes'),
    path('delete/<str:id>', views.delete_clothes, name='delete_clothes'),
    path('update/<str:id>',views.update_clothes, name="update_clothes"),
    path('filterclothes/', views.filter_clothes, name='filter_clothes'),
    path('filtertemp/<str:selected_weather>',views.filter_temp,name='filter_temp'),
    path('same_day/',views.same_day,name='same_day'),
]
    

weather_wear/weather_wear/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.core.exceptions import FieldDoesNotExist
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainPage.urls')),
    path('accounts/',include('allauth.urls')),
    path('myPage/', include('myPage.urls')),
    path('community/', include('community.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

weather_wear/myPage/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.deletion import CASCADE
import sys
sys.path.append("..")
from django.conf import settings
from datetime import datetime
from django.utils import timezone

# Create your models here.


#자기 착장 기록

class MyClothes(models.Model):
    id=models.AutoField(primary_key=True)
    #제목
    title=models.CharField(max_length=300)
    #날씨 카테고리
    WEATHER_CHOICE=(
        ('sunny','맑음'),
        ('cloud','흐림'),
        ('rain','비'),
        ('snow','눈'),
    )
    weather=models.CharField(max_length=20, choices=WEATHER_CHOICE, default="")
    #기온
    temperature=models.IntegerField(default=0)
    #날짜
    post_date=models.DateField(default=timezone.now)
    #작성자
    user=models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name="작성자", default="")
    thumbnail=models.ImageField(upload_to='images', blank=True, null=True, default="{%static 'images/blank.png' %}")
    memo=models.TextField(default="")


    def __str__(self):
        return self.title
    
    class Meta:
        db_table="MyClothes"

weather_wear/myPage/forms.py
from django import forms
from .models import MyClothes


class MyClothesPost(forms.ModelForm):
    class Meta:
        model=MyClothes
        fields='__all__'

 

weather_wear/myPage/views.py
from .models import MyClothes
from django.shortcuts import get_object_or_404, redirect, render
import sys
sys.path.append("..")
from accounts.models import UserProfile
from community.models import Community
from django.core.paginator import Paginator
from datetime import datetime
from django.contrib import messages
from django.db.models import Q
from django.views.generic import ListView
# Create your views here.

class ClothesListView(ListView):
    model=MyClothes


#마이페이지로 이동하는 함수
def mypage(request):
    return render(request, 'myPage/myPageMain.html')

#개인정보 페이지로 이동하는 함수
def profile(request):
    check = request.user.email
    profiles = UserProfile.objects.get(email = check)
    return render(request, 'myPage/myPageProfile.html', {'profiles':profiles})

#개인정보 수정 화면 연결 함수
def edit_profile(request):
    check = request.user
    profiles = UserProfile.objects.get(user = check)
    return render(request, 'myPage/edit_profile.html', {'profiles':profiles})

#수정된 개인정보
def update_profile(request):
    check = request.user
    update_profiles = UserProfile.objects.get(user = check)
    update_profiles.name = request.POST['name']
    update_profiles.email = request.POST['email']
    check.email = request.POST['email']
    update_profiles.gender = request.POST['gender']
    update_profiles.height = request.POST['height']
    update_profiles.bodyForm = request.POST['bodyForm']
    update_profiles.save()
    check.save()
    return redirect('myPage:profile')

# 커뮤니티에 작성한 글 페이지 나타나내는 함수
def writing_list(request):
    user = request.user
    selected_weather = "날씨전체"
    community = Community.objects.filter(writer = user).order_by('-pub_date')
    count = 0
    for i in community:
        count += 1
    page = int(request.GET.get('p',1))
    paginator = Paginator(community,10)
    boards = paginator.get_page(page)
    return render(request, 'myPage/writing_list.html',{'boards':boards, 'count':count,'selected_weather':selected_weather })

def filter_list(request):
    count = 0
    user = request.user
    if request.method == "POST":
        selected_weather = request.POST['weather']
        if selected_weather == "날씨전체":
            community = Community.objects.filter(writer = user).order_by('-pub_date')
            for i in community:
                count += 1
        else:
            community = Community.objects.filter(writer = user, weather = selected_weather).order_by('-pub_date')
            for i in community:
                count += 1
    page = int(request.GET.get('p',1))
    paginator = Paginator(community,3)
    boards = paginator.get_page(page)
    return render(request,'myPage/writing_list.html',{'boards':boards, 'count':count,'selected_weather':selected_weather })
#자기착장페이지로 이동
def my_clothes(request):
    user=request.user
    clothes=MyClothes.objects.filter(user=user).order_by('-post_date')
    check=request.user.email
    profiles=UserProfile.objects.get(email=check)
    selected_weather="all"
    page=int(request.GET.get('p',1))
    paginator=Paginator(clothes, 4)
    boards=paginator.get_page(page)
    return render(request, 'myPage/my_clothes.html',{'profiles':profiles, 'clothes':clothes, 'boards':boards , 'selected_weather':selected_weather})

#글쓰기
def new_clothes(request):
    check=request.user.email
    profiles=UserProfile.objects.get(email=check)
    return render(request, 'myPage/new_clothes.html',{'profiles':profiles})

#착장만들기
def create_clothes(request):
    new_clothes=MyClothes()
    new_clothes.title=request.POST['title']
    new_clothes.weather=request.POST['category_radio']
    new_clothes.temperature=request.POST['temperature']
    new_clothes.post_date=request.POST['post_date']
    new_clothes.thumbnail=request.FILES.get('thumbnail')
    new_clothes.user=request.user
    new_clothes.memo=request.POST['memo']
    new_clothes.save()
    return redirect('myPage:my_clothes')

def detail_clothes(request, id):
    clothes=get_object_or_404(MyClothes,pk=id)
    return render(request, 'myPage/detail_clothes.html',{'clothes':clothes})

 
def delete_clothes(request,id):
    delete=MyClothes.objects.get(id=id)
    delete.delete()
    return redirect('myPage:my_clothes')


def edit_clothes(request,id):
    edit=MyClothes.objects.get(id=id)
    return render(request, 'myPage/edit_clothes.html',{'clothes':edit})

def update_clothes(request, id):
    update_clothes=MyClothes.objects.get(id=id)
    update_clothes.title=request.POST['title']
    update_clothes.weather=request.POST['category_radio']
    update_clothes.temperature=request.POST['temperature']
    update_clothes.post_date=request.POST['post_date']
    update_clothes.thumbnail=request.FILES.get('thumbnail')
    update_clothes.user=request.user
    update_clothes.memo=request.POST['memo']
    update_clothes.save()
    return redirect('myPage:detail_clothes',update_clothes.id)

#날씨따라 분류
def filter_clothes(request):
    user = request.user
    if request.method == "POST":
        selected_weather = request.POST['weather']
        if selected_weather == "all": 
            return redirect('myPage:my_clothes')
        else:
            clothes=MyClothes.objects.filter(user=user, weather=selected_weather).order_by('-post_date')
            check=request.user.email
            profiles=UserProfile.objects.get(email=check)
            page=int(request.GET.get('p',1))
            paginator=Paginator(clothes, 4)
            boards=paginator.get_page(page)
            return render(request, 'myPage/my_clothes.html',{'profiles':profiles, 'clothes':clothes, 'boards':boards, "selected_weather":selected_weather})


def filter_temp(request, selected_weather): #selected_weather값 받음 >> template수정, url도 포함
    user=request.user
    temp=int(request.POST['temp'])#temp로 폼구성
    if request.method=='POST':
        if selected_weather=='all':
                clothes=MyClothes.objects.filter(user=user, temperature__gte=(temp-2),temperature__lte=(temp+2))
        else:
                clothes=MyClothes.objects.filter(user=user, temperature__gte=(temp-2), temperature__lte=(temp+2),weather=selected_weather)
    check=request.user.email
    profiles=UserProfile.objects.get(email=check)
    page=int(request.GET.get('p',1))
    paginator=Paginator(clothes, 4)
    boards=paginator.get_page(page)
    return render(request, 'myPage/my_clothes.html',{'profiles':profiles, 'clothes':clothes, 'boards':boards, "selected_weather":selected_weather})

def same_day(request):
    user=request.user
    today_month=datetime.today().month
    today_day=datetime.today().day
    clothes=MyClothes.objects.filter(user=user, post_date__month=today_month, post_date__day=today_day)
    check=request.user.email
    profiles=UserProfile.objects.get(email=check)
    page=int(request.GET.get('p',1))
    paginator=Paginator(clothes, 4)
    boards=paginator.get_page(page)
    selected_weather="all"
    return render(request, 'myPage/my_clothes.html',{'profiles':profiles, 'clothes':clothes, 'boards':boards, "selected_weather":selected_weather})

weather_wear/myPage/templates/myPage/my_clothes.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<link rel='stylesheet prefetch' href='https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css'>
<link rel='stylesheet prefetch' href='https://files.krve.io/f/eyespot.css'>
<link rel='stylesheet prefetch' href='https://cdn.cloudcache.dk/materialdesignicons/1.6.50/css/materialdesignicons.min.css'>
<section class="services-section spad" style="height: 100%;">
  <div class="row">
      <div class="col-lg-12">
          <div class="section-title">
              <span>Weather-wear</span>
              <h2>자기 착장 페이지</h2>
          </div>
      </div>
  </div>
  <div class="container">
    <div class="row">
    <!--카테고리 목록-->
    <div class="col-lg-3">
      <ul class="list-group help-group">
        <div class="faq-list list-group nav nav-tabs">
          <!-- 7개의 탭 -->
          <a href="{% url 'myPage:mypage' %}" class="list-group-item">
            마이페이지
          </a>
          <a href="{% url 'myPage:my_clothes' %}" class="list-group-item active" >
            <i class="mdi mdi-star"></i> 자기 착장 페이지
          </a>
          <a href="{% url 'myPage:writing_list' %}" class="list-group-item">
            <i class="mdi mdi-star"></i> 커뮤니티에 작성한 글
          </a>
          <a href="{% url 'myPage:profile' %}" class="list-group-item">
            <i class="mdi mdi-account"></i> 개인정보
          </a>
        </div>
      </ul>
    </div>
    <div class="col-lg-8">
        <!-- Page content-->
        <div class="container-fluid">
          <a class="btn btn-primary" href="{%url 'myPage:new_clothes'  %}">WRITE</a>
          <a class="btn btn-primary" href="{%url 'myPage:same_day'  %}" >n년 전 오늘</a>
          <br><br>
          <div id='btnclear'>
            <form method="post" action="{% url 'myPage:filter_clothes' %}">
                {% csrf_token %}
                <select name="weather">
                    <option value="{{selected_weather}}" class ='fw-bolder'>{{selected_weather}}</option>
                    <option value="all">날씨전체</option>
                    <option value="sunny">맑음</option>
                    <option value="rain">비</option>
                    <option value="cloud">흐림</option>
                    <option value="snow">눈</option>
                </select>
                <input class="button" type="submit" value="카테고리 검색" >
            </form>
        </div>
        &nbsp;
          <div id='btnclear'>
            <form method="post" action="{% url 'myPage:filter_temp' selected_weather%}">
                {% csrf_token %}
                <input type="number" min="-20" max="50" name="temp" style="width:50px;">
                <input class="button" type="submit" value="온도 검색">
            </form>
        </div>       
        </div>
        <br><br>
    </div>
    <br>
    <div class="col--8">
        <!-- Page content-->
        <div class="container">
            <div class="row">
                <div class="col-lg-3"></div>
                <!-- Blog entries-->
                <div class="col-lg-8">
                    <div class="row">
                      <!-- Blog post-->
                        {% for c in boards %} 
                            <div class="card mb-4" style="width:45%; background: #222222;">
                               <img class="card-img-top"  style="width:auto; max-height:400px;"src="{% if c.thumbnail %}{{ c.thumbnail.url }}{% else %}#{% endif %}" alt="..." />
                                <div class="card-body">
                                    <div class="sub small text-muted">{{c.post_date}}</div>
                                    <h2 class="sub card-title h4 fw-bolder">{{c.title}}</h2>
                                    <h4 class="sub">{{c.weather}}</h4>
                                    <h5 class="sub">{{c.temperature}}˚C</h5>
                                    <a class="btn btn-primary" href="{%url 'myPage:detail_clothes' c.id %}">Read more →</a>
                                </div>
                            </div>    
                        {% endfor %}   
                    </div>
                </div>
            </div>
        </div>
        <div class = "row mt-2" style="text-align: center;">
          <div class = "col-12">
            <nav>
              <ul class = "pagination justify-content-center">
                  {% if boards.has_previous %}
                      <li class = "page-item">
                          <a class = "page-link" href = "?p={{boards.previous_page_number}}">이전</a>
                      </li>
                  {% else %}
                      <li class = "page-item disabled">
                          <a class = "page-link disabled" href = "#">이전</a>
                      </li>
                  {% endif %}
                  <li class = "page-item active">
                      <a class = "page-link" style="background: #e32879; border: #e32879 1px solid;">{{boards.number}}/{{boards.paginator.num_pages}}</a>
                  </li>
                  {% if boards.has_next %}
                      <li class = "page-item">
                          <a class = "page-link" href = "?p={{boards.next_page_number}}">다음</a>
                      </li>
                  {% else %}
                      <li class = "page-item disabled">
                          <a class = "page-link disabled" href = "#">다음</a>
                      </li>
                  {% endif %}
              </ul>
            </nav>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- Bootstrap core JS-->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"></script>
<!-- Core theme JS-->
<script src="js/scripts.js"></script>
<style type="text/css">
    a:hover, a:focus{
      text-decoration: none;
    }
    .list-group.help-group {
      margin-bottom: 20px;
      padding-left: 0;
      margin: 0;
    }
    .list-group.help-group .faq-list {
      display: block;
      top: auto;
      margin: 0 0 32px;
      border-radius: 2px;
      border: 1px solid #ddd;
      box-shadow: 0 1px 5px rgba(85, 85, 85, 0.15);
    }
    .list-group.help-group .faq-list .list-group-item {
      position: relative;
      display: block;
      margin: 0;
      padding: 13px 16px;
      background-color: #fff;
      border: 0;
      border-bottom: 1px solid #ddd;
      border-top-left-radius: 2px;
      border-top-right-radius: 2px;
      color: #616161;
      transition: background-color .2s;
    }
    .list-group.help-group .faq-list .list-group-item i.mdi {
      margin-right: 5px;
      font-size: 18px;
      position: relative;
      top: 2px;
    }
    .list-group.help-group .faq-list .list-group-item:hover {
      background-color: #f6f6f6;
    }
    .list-group.help-group .faq-list .list-group-item.active {
      background-color: #f6f6f6;
      font-weight: 700;
      color: rgba(0, 0, 0, 0.87);
    }
    .list-group.help-group .faq-list .list-group-item:last-of-type {
      border-bottom-left-radius: 2px;
      border-bottom-right-radius: 2px;
      border-bottom: 0;
    }
    
    .tab-content.panels-faq {
      padding: 0;
      border: 0;
    }
    
    .panel.panel-help {
      box-shadow: 0 1px 5px rgba(85, 85, 85, 0.15);
      padding-bottom: 0;
      border-radius: 2px;
      overflow: hidden;
      background-color: #fff;
      margin: 0 0 16px;
    }
    .panel.panel-help a[href^="{% url 'myPage:my_clothes' %}"],
    .panel.panel-help a[href^="#"]:hover,
    .panel.panel-help a[href^="#"]:focus {
      outline: none;
      cursor: pointer;
      text-decoration: none;
    }
    .panel.panel-help .panel-heading {
      background-color: #f6f6f6;
      padding: 0 16px;
      line-height: 48px;
      border-top-right-radius: 2px;
      border-top-left-radius: 2px;
      color: rgba(0, 0, 0, 0.87);
    }
    .panel.panel-help .panel-heading h2 {
      margin: 0;
      padding: 14px 0 14px;
      font-size: 18px;
      font-weight: 400;
      line-height: 20px;
      letter-spacing: 0;
      text-transform: none;
    }
    .panel.panel-help .panel-body {
      background-color: #fff;
      border-top: 1px solid #ddd;
      border-radius: 2px;
      border-top-right-radius: 0;
      border-top-left-radius: 0;
      margin-top: 0;
    }
    .panel.panel-help .panel-body p {
      margin: 0 0 16px;
    }
    .panel.panel-help .panel-body p:last-of-type {
      margin: 0;
    }
    .profile {
  border-collapse: collapse;
  text-align: left;
  line-height: 1.5;
  border-left: 1px solid #ccc;
}

.profile thead th {
  padding: 10px;
  font-weight: bold;
  border-top: 1px solid #ccc;
  border-right: 1px solid #ccc;
  border-bottom: 2px solid #c00;
  background: #dcdcd1;
}
.profile tbody th {
  width: 150x;
  padding: 10px;
  font-weight: bold;
  vertical-align: top;
  border-right: 1px solid #ccc;
  border-bottom: 1px solid #ccc;
  background: #ececec;
}
.profile td {
  width: 350px;
  padding: 10px;
  vertical-align: top;
  border-right: 1px solid #ccc;
  border-bottom: 1px solid #ccc;
  background: white;
}
.thumbanil{
  max-width: 500px;
  height:auto;
}
.btn{
  background: #e32879;
  border: none;
}
.button{
  background: #e32879;
  border: none;
  color:#fff;
}
.sub{
  color:#fff;
}
input::-webkit-outer-spin-button,
input::-webkit-inner-spin-button {
  -webkit-appearance: none;
}
    </style>
{%endblock%}

weather_wear/myPage/templates/myPage/writing_list.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<link rel='stylesheet prefetch' href='https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css'>
<link rel='stylesheet prefetch' href='https://files.krve.io/f/eyespot.css'>
<link rel='stylesheet prefetch' href='https://cdn.cloudcache.dk/materialdesignicons/1.6.50/css/materialdesignicons.min.css'>
<section class="services-section spad" style="height: 100%;">
  <div class="row">
      <div class="col-lg-12">
          <div class="section-title">
              <span>Weather-wear</span>
              <h2>community에 작성한 글</h2>
          </div>
      </div>
  </div>
  <div class="container">
    <div class="row">
    <!--카테고리 목록-->
    <div class="col-lg-3">
      <ul class="list-group help-group">
        <div class="faq-list list-group nav nav-tabs">
          <!-- 7개의 탭 -->
          <a href="{% url 'myPage:mypage' %}" class="list-group-item">
            마이페이지
          </a>
          <a href="{% url 'myPage:my_clothes' %}" class="list-group-item" >
            <i class="mdi mdi-star"></i> 자기 착장 페이지
          </a>
          <a href="{% url 'myPage:writing_list' %}" class="list-group-item active">
            <i class="mdi mdi-star"></i> 커뮤니티에 작성한 글
          </a>
          <a href="{% url 'myPage:profile' %}" class="list-group-item">
            <i class="mdi mdi-account"></i> 개인정보
          </a>
        </div>
      </ul>
    </div>
    <div class="col-lg-9">
        <!-- Page content-->
        <div class="container-fluid" style="width: 100%;">
            <div>
                <p>작성한 글의 수 : {{count}}</p>
                <form method="post" action="{% url 'myPage:filter_list' %}">
                    {% csrf_token %}
                    <select name="weather">
                        <option value="{{selected_weather}}">{{selected_weather}}</option>
                        <option value="날씨전체">날씨전체</option>
                        <option value="맑음">맑음</option>
                        <option value="비">비</option>
                        <option value="흐림">흐림</option>
                        <option value="우박">우박</option>
                        <option value="눈">눈</option>
                        <option value="안개">안개</option>
                        <option value="소나기">소나기</option>
                    </select>
                    <input class="button" type="submit" value="검색">
                </form>
            </div><br>
            <table class="table" >
              <thead>
                  <tr class="thead-blue">
                    <th scope="cols" width=10%>순번</th>
                    <th scope="cols" width=35%>제목</th>
                    <th scope="cols" width=10%>날씨</th>
                    <th scope="cols" width=30%>날짜</th>
                    <th scope="cols" width=15%>조회수</th>  
                  </tr>
              </thead>
              <tbody>
                {% for community in boards %} 
                <tr class="list" onclick="location.href='{% url 'community:detail' community.id %}'">
                    <td>{{ forloop.counter }}</td>
                    <td class="title">{{ community.title }}</td>
                    <td>{{ community.weather }}</td>
                    <td>{{ community.pub_date }}</td>
                    <td>{{ community.view_count }}</td>    
                </tr>
                {% endfor %}
                </tbody>
          </table>
        </div>
        <br>
        <!--밑에 버튼-->
        <div class = "row mt-2" style="text-align: center;">
            <div class = "col-12">
                <nav>
                    <ul class = "pagination justify-content-center">
                        {% if boards.has_previous %}
                            <li class = "page-item">
                                <a class = "page-link" href = "?p={{boards.previous_page_number}}">이전</a>
                            </li>
                        {% else %}
                            <li class = "page-item disabled">
                                <a class = "page-link disabled" href = "#">이전</a>
                            </li>
                        {% endif %}
        
                        <li class = "page-item active">
                            <a class = "page-link" style="background: #e32879; border: none;">{{boards.number}}/{{boards.paginator.num_pages}}</a>
                        </li>
        
                        {% if boards.has_next %}
                            <li class = "page-item">
                                <a class = "page-link" href = "?p={{boards.next_page_number}}">다음</a>
                            </li>
                        {% else %}
                            <li class = "page-item disabled">
                                <a class = "page-link disabled" href = "#">다음</a>
                            </li>
                        {% endif %}
                    </ul>
                </nav>
            </div>
        </div>
    </div>
</div>
<!-- Bootstrap core JS-->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"></script>
<!-- Core theme JS-->
<script src="js/scripts.js"></script>
<style type="text/css">
    a:hover, a:focus{
      text-decoration: none;
    }
    .list-group.help-group {
      margin-bottom: 20px;
      padding-left: 0;
      margin: 0;
    }
    .list-group.help-group .faq-list {
      display: block;
      top: auto;
      margin: 0 0 32px;
      border-radius: 2px;
      border: 1px solid #ddd;
      box-shadow: 0 1px 5px rgba(85, 85, 85, 0.15);
    }
    .list-group.help-group .faq-list .list-group-item {
      position: relative;
      display: block;
      margin: 0;
      padding: 13px 16px;
      background-color: #fff;
      border: 0;
      border-bottom: 1px solid #ddd;
      border-top-left-radius: 2px;
      border-top-right-radius: 2px;
      color: #616161;
      transition: background-color .2s;
    }
    .list-group.help-group .faq-list .list-group-item i.mdi {
      margin-right: 5px;
      font-size: 18px;
      position: relative;
      top: 2px;
    }
    .list-group.help-group .faq-list .list-group-item:hover {
      background-color: #f6f6f6;
    }
    .list-group.help-group .faq-list .list-group-item.active {
      background-color: #f6f6f6;
      font-weight: 700;
      color: rgba(0, 0, 0, 0.87);
    }
    .list-group.help-group .faq-list .list-group-item:last-of-type {
      border-bottom-left-radius: 2px;
      border-bottom-right-radius: 2px;
      border-bottom: 0;
    }
    
    .tab-content.panels-faq {
      padding: 0;
      border: 0;
    }
    
    .panel.panel-help {
      box-shadow: 0 1px 5px rgba(85, 85, 85, 0.15);
      padding-bottom: 0;
      border-radius: 2px;
      overflow: hidden;
      background-color: #fff;
      margin: 0 0 16px;
    }
    .panel.panel-help a[href^="#"],
    .panel.panel-help a[href^="#"]:hover,
    .panel.panel-help a[href^="#"]:focus {
      outline: none;
      cursor: pointer;
      text-decoration: none;
    }
    .panel.panel-help .panel-heading {
      background-color: #f6f6f6;
      padding: 0 16px;
      line-height: 48px;
      border-top-right-radius: 2px;
      border-top-left-radius: 2px;
      color: rgba(0, 0, 0, 0.87);
    }
    .panel.panel-help .panel-heading h2 {
      margin: 0;
      padding: 14px 0 14px;
      font-size: 18px;
      font-weight: 400;
      line-height: 20px;
      letter-spacing: 0;
      text-transform: none;
    }
    .panel.panel-help .panel-body {
      background-color: #fff;
      border-top: 1px solid #ddd;
      border-radius: 2px;
      border-top-right-radius: 0;
      border-top-left-radius: 0;
      margin-top: 0;
    }
    .panel.panel-help .panel-body p {
      margin: 0 0 16px;
    }
    .panel.panel-help .panel-body p:last-of-type {
      margin: 0;
    }
.thumbanil{
  max-width: 500px;
  height:auto;
}
table{
  border-top: 1px solid #fff;
  border-bottom: 1px solid #fff;
}
td, th {
  color:#fff;
}
.title:hover{
  color:#e32879;
}
.button{
  background: #e32879;
  color:#fff;
  border: none;
  width: 60px;
  border-radius: 10px;
  height: 30px;
}
select{
  width: 100px;
  height: 30px;
}
</style>
{%endblock%}