weather_wear/community/urls.py
from django.urls import path
from .views import *

app_name = "community"
urlpatterns = [
    path('', show, name="show"),
    path('<str:id>', detail, name="detail"),
    path('new/', new, name="new"),
    path('create/', create, name="create"),
    path('edit/<str:id>', edit, name="edit"),
    path('update/<str:id>', update, name="update"),
    path('delete/<str:id>', delete, name="delete"),
    path('<str:community_id>/create_comment', create_comment, name="create_comment"),
    path('<int:comment_id>/update_comment', update_comment, name="update_comment"),
    path('<int:comment_id>/delete_comment', delete_comment, name="delete_comment"),
    path('<int:community_id>/community_like', community_like, name="community_like"),
]

weather_wear/mainPage/urls.py
from django.urls import path
from .views import *

app_name = "mainPage"
urlpatterns = [
    path('', mainpage , name="mainpage"),
    path('today/', today, name="today"),
]

weather_wear/myPage/urls.py
from django.urls import path
from . import views

app_name = "myPage"
urlpatterns = [
    path('',views.mypage, name="mypage"),
    path('profile/', views.profile, name="profile"),
    path('edit/', views.edit_profile, name="edit"),
    path('update/', views.update_profile, name="update"),
    path('writing_list/', views.writing_list, name="writing_list"),
    path('filter_list/', views.filter_list, name="filter_list"),
    path('myclothes/', views.my_clothes, name='my_clothes'),
    path('newclothes/', views.new_clothes, name='new_clothes'),
    path('createclothes/',views.create_clothes, name='create_clothes'),
    path('<str:id>',views.detail_clothes, name="detail_clothes"),
    path('edit/<str:id>', views.edit_clothes, name='edit_clothes'),
    path('delete/<str:id>', views.delete_clothes, name='delete_clothes'),
    path('update/<str:id>',views.update_clothes, name="update_clothes"),
    path('filterclothes/', views.filter_clothes, name='filter_clothes'),
    path('filtertemp/<str:selected_weather>',views.filter_temp,name='filter_temp'),
    path('same_day/',views.same_day,name='same_day'),
]
    

weather_wear/weather_wear/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.core.exceptions import FieldDoesNotExist
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainPage.urls')),
    path('accounts/',include('allauth.urls')),
    path('myPage/', include('myPage.urls')),
    path('community/', include('community.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

weather_wear/templates/base.html
{% load static %}
<!DOCTYPE html>

<html lang="ko">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.8.2/css/all.min.css"/>

    {% include 'head.html' %}

    <body style="background: #191919">
        {% include 'header.html' %}

        {% block content %}

        {% endblock %}
        
        <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
        <script src="{% static 'js/bootstrap.min.js' %}"></script>
        <script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
        <script src="{% static 'js/mixitup.min.js' %}"></script>
        <script src="{% static 'js/jquery.slicknav.js' %}"></script>
        <script src="{% static 'js/owl.carousel.min.js' %}"></script>
        <script src="{% static 'js/main.js' %}"></script>
    </body>

weather_wear/templates/footer.html
<!--Footer-->
<footer class="py-5">
    <div class="container"><p class="m-0 text-center text-white">Copyright &copy; Ideathon Weather_wear</p></div>
</footer>
<style>
footer {
    width:100%;
    height:80px;
    position: absolute;
    bottom: 0;
    background:#191919;
    text-align: center;
    color: white;
 }
 </style>

weather_wear/templates/head.html
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="description" content="Hazze Template">
    <meta name="keywords" content="Hazze, unica, creative, html">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Weather-wear</title>

    <!-- Google Font -->
    <link href="https://fonts.googleapis.com/css?family=Libre+Franklin:400,500,600,700,800,900&display=swap"
        rel="stylesheet">

    <!-- Css Styles -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/themify-icons.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/slicknav.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}?abcde" type="text/css">
</head>

weather_wear/templates/header.html
{% load static %}

<!-- Navigation-->
<header class="header-section">
    <div class="container">
        <div class="row">
            <div class="col-lg-2 col-md-2">
                <div class="logo">
                    <a href="{% url 'mainPage:mainpage' %}">
                        <img src="{% static 'images/logo.png' %}" alt="">
                    </a>
                </div>
            </div>
            <div class="col-lg-10 col-md-10">
                <div class="main-menu mobile-menu">
                    <ul>
                        <li><a href="{% url 'mainPage:today' %}">오늘의 옷 추천</a></li>
                        <li><a href="{% url 'community:show' %}">community</a></li>
                        {% if user.is_authenticated %}
                        {% if user.is_superuser %}
                        <li><a href="{% url 'account_logout' %}">로그아웃</a></li>
                        {% else %}
                        <li><a href="{% url 'myPage:mypage' %}">마이페이지</a></li>
                        <li><a href="{% url 'account_logout' %}">로그아웃</a></li>
                        {% endif %}
                        {% else %}
                        <li><a href="{% url 'account_login' %}">로그인</a></li>
                        <li><a href="{% url 'account_signup' %}">회원가입</a></li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </div>
        <div id="mobile-menu-wrap"></div>
    </div>
</header>