weather_wear/community/urls.py
from django.urls import path
from .views import *

app_name = "community"
urlpatterns = [
    path('', show, name="show"),
    path('<str:id>', detail, name="detail"),
    path('new/', new, name="new"),
    path('create/', create, name="create"),
    path('edit/<str:id>', edit, name="edit"),
    path('update/<str:id>', update, name="update"),
    path('delete/<str:id>', delete, name="delete"),
    path('<str:community_id>/create_comment', create_comment, name="create_comment"),
    path('<int:comment_id>/update_comment', update_comment, name="update_comment"),
    path('<int:comment_id>/delete_comment', delete_comment, name="delete_comment"),
    path('<int:community_id>/community_like', community_like, name="community_like"),
]

weather_wear/myPage/urls.py
from django.urls import path
from . import views

app_name = "myPage"
urlpatterns = [
    path('',views.mypage, name="mypage"),
    path('profile/', views.profile, name="profile"),
    path('edit/', views.edit_profile, name="edit"),
    path('update/', views.update_profile, name="update"),
    path('writing_list/', views.writing_list, name="writing_list"),
    path('filter_list/', views.filter_list, name="filter_list"),
    path('myclothes/', views.my_clothes, name='my_clothes'),
    path('newclothes/', views.new_clothes, name='new_clothes'),
    path('createclothes/',views.create_clothes, name='create_clothes'),
    path('<str:id>',views.detail_clothes, name="detail_clothes"),
    path('edit/<str:id>', views.edit_clothes, name='edit_clothes'),
    path('delete/<str:id>', views.delete_clothes, name='delete_clothes'),
    path('update/<str:id>',views.update_clothes, name="update_clothes"),
    path('filterclothes/', views.filter_clothes, name='filter_clothes'),
    path('filtertemp/<str:selected_weather>',views.filter_temp,name='filter_temp'),
    path('same_day/',views.same_day,name='same_day'),
]
    

weather_wear/weather_wear/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.core.exceptions import FieldDoesNotExist
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainPage.urls')),
    path('accounts/',include('allauth.urls')),
    path('myPage/', include('myPage.urls')),
    path('community/', include('community.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

weather_wear/community/models.py
from django.db import models
from django.contrib.auth.models import User

class Community(models.Model):
    WEATHER = (
        ('맑음', '맑음'),
        ('비', '비'),
        ('흐림', '흐림'),
        ('우박', '우박'),
        ('눈', '눈'),
        ('안개', '안개'),
        ('소나기', '소나기')
    )

    GENDER = (
        ('남자', '남자'),
        ('여자', '여자')
    )
    id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=200)
    writer = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    pub_date = models.DateTimeField()
    body = models.TextField()
    image = models.ImageField(upload_to="community/", blank=True, null=True)
    view_count = models.PositiveIntegerField(default = 0)
    weather = models.CharField(max_length=80, choices=WEATHER)
    gender = models.CharField(max_length=2, choices=GENDER)
    like_user_set = models.ManyToManyField(User, blank=True, related_name="like_user_set", through="Like")

    def __str__(self):
        return self.title

    def summary(self):
        return self.body[:20]

    @property
    def like_count(self):
        return self.like_user_set.count()

class Comment(models.Model):
    content = models.TextField()
    writer = models.ForeignKey(User, on_delete=models.CASCADE)
    community = models.ForeignKey(Community, on_delete=models.CASCADE, related_name='comments')
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now=True)

class Like(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    community = models.ForeignKey(Community, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        unique_together = (('user','community'))

weather_wear/community/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Community, Comment, Like
from django.utils import timezone
from django.contrib.auth.decorators import login_required
from .filters import CommunityFilter
from django.db.models import Count
from django.core.paginator import Paginator

def show(request):

    context = {}

    sort = request.GET.get('sort', '')

    if sort == 'likes':
        filtered_community = CommunityFilter(
            queryset = Community.objects.all().annotate(likes=Count('like_user_set')).order_by('-likes')
        )
    elif sort == 'views':
        filtered_community = CommunityFilter(
            queryset=Community.objects.order_by('-view_count'),
        )
    else:    
        filtered_community = CommunityFilter(
            request.GET, 
            queryset=Community.objects.order_by('-pub_date'),
            
        )

    context['filtered_community'] = filtered_community

    paginated_filtered_persons = Paginator(filtered_community.qs, 7)
    page_number = request.GET.get('page')
    person_page_obj = paginated_filtered_persons.get_page(page_number)

    context['person_page_obj'] = person_page_obj

    return render(request, 'community/show.html', context=context)

def detail(request, id):
    community = get_object_or_404(Community, id = id) 
    all_comments = community.comments.order_by('-created_at')
    community.view_count += 1
    community.save()
    return render(request, 'community/detail.html', {'community':community, 'comments':all_comments})

def new(request):
    return render(request, 'community/new.html')    

def create(request):
    new_community = Community()
    new_community.title = request.POST['title']
    new_community.writer = request.user
    new_community.pub_date = timezone.now()
    new_community.body = request.POST['body']
    new_community.image = request.FILES.get('image')
    new_community.weather = request.POST['weather']
    new_community.gender = request.POST['gender']
    new_community.save()
    return redirect('community:detail', new_community.id)

def edit(request, id):
    edit_community = Community.objects.get(id = id)
    return render(request, 'community/edit.html', {'community': edit_community})

def update(request, id):
    update_community = Community.objects.get(id = id)
    update_community.title = request.POST['title']
    update_community.writer = request.user
    update_community.pub_date = timezone.now()
    update_community.body = request.POST['body']
    update_community.image = request.FILES.get('image')
    update_community.weather = request.POST['weather']
    update_community.gender = request.POST['gender']
    update_community.save()
    return redirect('community:detail', update_community.id)

def delete(request, id):
    delete_community = Community.objects.get(id = id)
    delete_community.delete()
    return redirect('community:show')

def create_comment(request, community_id):
    if request.method == "POST":
        community = get_object_or_404(Community, pk=community_id)
        current_user = request.user
        comment_content = request.POST.get('content')
        Comment.objects.create(content=comment_content, writer=current_user, community=community)
    return redirect('community:detail', community_id)

def update_comment(request, comment_id):
    comment=get_object_or_404(Comment, pk=comment_id)
    if request.method == "POST":
        community_id = comment.community.id
        comment.content=request.POST.get('content')
        comment.save()
        return redirect('community:detail', community_id)
    return render(request, 'community/update_comment.html',{"comment":comment})

def delete_comment(request, comment_id):
    comment = get_object_or_404(Comment, pk=comment_id)
    community_id = comment.community.id
    comment.delete()
    return redirect('community:detail', community_id)

@login_required
def community_like(request, community_id):
    community = get_object_or_404(Community, pk=community_id)

    #좋아요 확인
    if request.user in community.like_user_set.all():
        community.like_user_set.remove(request.user)
    else:
        community.like_user_set.add(request.user)

    if request.GET.get('redirect_to')=='detail':
        return redirect('community:detail', community_id)
    else:
        return redirect('community:show')

weather_wear/community/templates/community/detail.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<section class="services-section spad">
    <div class="row">
        <div class="col-lg-12">
            <div class="section-title" style="margin-bottom: 30px;">
                <h2>{{community.title}}</h2>
            </div>
        </div>
    </div>
    <div class="container">
        <p>날씨 : {{community.weather}}</p>
        <p>성별 : {{community.gender}}</p>

        <p>조회수 : {{ community.view_count }}</p>
        {% if community.writer %}
            <p>작성자 : {{ community.writer }}</p>
        {% else %}
            <p>작성자 : 알 수 없음</p>
        {% endif %}
        <p>작성일시 : {{community.pub_date}}</p>
        <a href ="{% url 'community:community_like' community.id %}?redirect_to=detail">
            {% if user in community.like_user_set.all %}
                <i class="fas fa-heart"></i>
            {% else %}
                <i class="far fa-heart"></i>
            {% endif %}
        </a>
        <div class="row">
        <div class="col-lg-6">
            <div class="as-pic">
                {% if community.image %}
                <div class="image" style="background: #222222;"><img src="{{ community.image.url }}" style="width: 570px; height:430px; object-fit: contain;" alt="사진"></div>
                {% else %}
                <div class="image" style="background: #222222;"><img src="{% static 'images/blank.png' %}" style="width: 570px; height:430px; object-fit: contain;" alt="사진"></div>
                {% endif %}
            </div>
        </div>
        <div class="col-lg-6">
            <div class="as-text ap-text">
                <p class="f-para">{{community.body}}</p>
            </div>
        </div>
        </div>
        <center>
            {% if user == community.writer %}
            <button><a href="{% url 'community:edit' community.id %}">수정하기</a></button>
            <button><a href="{% url 'community:delete' community.id %}">삭제하기</a></button>
            {% endif %}
            <button><a href="{% url 'community:show' %}">목록</a></button>
        </center>

        <center>
            <form action="{% url 'community:create_comment' community.id %}" method = "POST">
                {% csrf_token %}
                <textarea name="content" placeholder = "댓글 내용 입력" style="width:1100px"></textarea>
                <button type="submit" value="확인">댓글</button>
            </form>
        </center>
        <div>
            {% for comment in comments %}
            <div>
                <p>작성자 : {{comment.writer}}</p>   <p style="font-size: small;">{{comment.created_at}}</p>
                <p>{{comment.content}}</p>
                {% if user == comment.writer %}
                    <button><a href="{% url 'community:update_comment' comment.id %}">댓글 수정</a></button>
    			    <button><a href="{% url 'community:delete_comment' comment.id %}">댓글 삭제</a></button>
    			{% endif %}<hr>
            </div>
            {% endfor %}
        </div>
    </div>
</section>
<style>
    hr{
        background:#fff;
    }
    center{
        margin-bottom: 10px;
    }
    .row{
        margin-bottom: 15px;
    }
    a{
        color:#e32879;
    }
    p{
        margin-bottom: 0px;
    }
    button{
        background:#e32879;
        border: none;
        color:#fff;
        border-radius: 5px;
    }
    button a{
        color:#fff;
    }
    .f-para{
        word-break: break-all;
    }
</style>
{% endblock %}

weather_wear/community/templates/community/edit.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<section class="services-section spad" style="height: 100%;">
    <div class="row">
        <div class="col-lg-12">
            <div class="section-title" style="margin-bottom: 30px;">
                <img src="{% static 'images/write.png' %}">
                <h2>글 수정</h2>
            </div>
        </div>
    </div>
    <div class="col-lg-6" style="margin-right: auto; margin-left: auto;">
    <div class="write service-item">        
        <form action="{% url 'community:update' community.id %}" method="post" enctype="multipart/form-data">
            {%csrf_token%}
            <table>
                <tr>
                    <td class="subject">제목</td>
                    <td><textarea type="text" name="title" cols="30" rows="1">{{community.title}}</textarea></td>
                </tr>
                <tr>
                    <td class="gender subject">성별</td>
                    <td>
                        <select name="gender">
                            <option disabled>---성별---</option>
                            <option value="남자">남자</option>
                            <option value="여자">여자</option>
                        </select>
                    </td>
                </tr>
                <tr>
                    <td class="weather">날씨</td>
                    <td>
                        <select name="weather">
                            <option disabled>------날씨------</option>
                            <option value="맑음">맑음</option>
                            <option value="비">비</option>
                            <option value="흐림">흐림</option>
                            <option value="우박">우박</option>
                            <option value="눈">눈</option>
                            <option value="안개">안개</option>
                            <option value="소나기">소나기</option>
                        </select>
                    </td>
                </tr>
                <tr>
                    <td class="subject">사진</td>
                    <td><input type="file" name = "image"></td>
                </tr>
                <tr>
                    <td class="subject">내용</td>
                    <td><textarea type="text" name="body" id="" cols="45" rows="10">{{community.body}}</textarea></td>
                </tr>
                <tr>
                    <td class="button" colspan="2"><button type="submit">수정</button></td>
                </tr>
            </table>
        </form>       
    </div>
</section>
<style>
.write{
    height: fit-content;
    background: #222222;
}
table{
    margin-left: auto;
    margin-right: auto;    
}
table td{
    color:#fff;
    padding-bottom: 20px;
    text-align: left;
}
.subject{
    width: 20%;
}
.button{
    text-align: center;
}
.button button{
    background: #e32879;
    color:#fff;
    border: none;
    border-radius: 10px;
}
</style>
{% endblock %}

weather_wear/community/templates/community/new.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<section class="services-section spad" style="height: 100%;">
    <div class="row">
        <div class="col-lg-12">
            <div class="section-title" style="margin-bottom: 30px;">
                <img src="{% static 'images/write.png' %}">
                <h2>글작성</h2>
            </div>
        </div>
    </div>
    <div class="col-lg-6" style="margin-right: auto; margin-left: auto;">
    <div class="write service-item">        
        <form action="{% url 'community:create' %}" method="post" enctype="multipart/form-data">
            {%csrf_token%}
            <table>
                <tr>
                    <td class="subject">제목</td>
                    <td><textarea type="text" name="title" cols="30" rows="1"></textarea></td>
                </tr>
                <tr>
                    <td class="gender subject">성별</td>
                    <td>
                        <select name="gender">
                            <option disabled>---성별---</option>
                            <option value="남자">남자</option>
                            <option value="여자">여자</option>
                        </select>
                    </td>
                </tr>
                <tr>
                    <td class="weather">날씨</td>
                    <td>
                        <select name="weather">
                            <option disabled>------날씨------</option>
                            <option value="맑음">맑음</option>
                            <option value="비">비</option>
                            <option value="흐림">흐림</option>
                            <option value="우박">우박</option>
                            <option value="눈">눈</option>
                            <option value="안개">안개</option>
                            <option value="소나기">소나기</option>
                        </select>
                    </td>
                </tr>
                <tr>
                    <td class="subject">사진</td>
                    <td><input type="file" name = "image"></td>
                </tr>
                <tr>
                    <td class="subject">내용</td>
                    <td><textarea type="text" name="body" id="" cols="45" rows="10"></textarea></td>
                </tr>
                <tr>
                    <td class="button" colspan="2"><button type="submit">제출</button></td>
                </tr>
            </table>
        </form>       
    </div>
</section>
<style>
.write{
    height: fit-content;
    background: #222222;
}
table{
    margin-left: auto;
    margin-right: auto;    
}
table td{
    color:#fff;
    padding-bottom: 20px;
    text-align: left;
}
.subject{
    width: 20%;
}
.button{
    text-align: center;
}
.button button{
    background: #e32879;
    color:#fff;
    border: none;
    border-radius: 10px;
}
</style>
{% endblock %}

weather_wear/community/templates/community/show.html
{% extends "base.html" %}
{% block content %}
{% load static %}
{% if user.is_authenticated %}
<section class="services-section spad" style="height: 100%;">
    <div class="row">
        <div class="col-lg-12">
            <div class="section-title">
                <span>Weather-wear</span>
                <h2>community</h2>
            </div>
        </div>
    </div>
{% load community_extras %}  
<div class="container my-3">  
    <select id="sort-select" onchange="location = this.value;">
        {% if "/?sort=likes" in request.get_full_path %}	
            <option class="sort-new" value="?sort=new">최신순</option>	
            <option class="sort-likes" value="?sort=likes" selected >좋아요순</option>
            <option class="sort-views" value="?sort=views">조회순</option>
        {% elif "/?sort=views" in request.get_full_path %}	
            <option class="sort-new" value="?sort=new">최신순</option>	
            <option class="sort-likes" value="?sort=likes">좋아요순</option>
            <option class="sort-views" value="?sort=views" selected>조회순</option>
        {% else %}
            <option class="sort-new" value="?sort=new" selected >최신순</option>
             <option class="sort-likes" value="?sort=likes">좋아요순</option>	
             <option class="sort-views" value="?sort=views">조회순</option>
        {% endif %}
    </select>
    </div> 
<div class="container my-3">
    <form method="get">
        <p>{{ filtered_community.form.as_p }}</p>
        <button class="search" type="submit">검색</button><br><br>
    </form>

    <table class="table">
        <thead>
            <tr class="thead-blue">
                <th>성별</th>
                <th>날씨</th>
                <th>작성자</th>
                <th>제목</th>
                <th>작성일시</th>
                <th>조회수</th>
                <th>좋아요</th>
            </tr>
        </thead>
        <tbody>
            {% for community in person_page_obj %}
            <tr>
                <td>{{community.gender}}</td>
                <td>{{community.weather}}</td>
                <td>{{community.writer}}</td>
                <td class="title">
                    <a href="{% url 'community:detail' community.id %}">
                        {{community.title}}
                    </a>
                </td>
                <td>{{community.pub_date}}</td>
                <td style="text-align: center;">{{community.view_count}}</td>
                <td style="text-align: center;"><a href ="{% url 'community:community_like' community.id %}">
                    {% if user in community.like_user_set.all %}
                        <i class="fas fa-heart"></i>
                    {% else %}
                        <i class="far fa-heart"></i>
                    {% endif %}
                </a></td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    <button class="write"><a href="{% url 'community:new' %}">글쓰기</a></button>
</div>
<div class = "row mt-2" style="text-align: center;">
    <div class = "col-12">
        <nav>
            <ul class = "pagination justify-content-center">
                {% if person_page_obj.has_previous %}
                    <li class = "page-item">
                        <a class = "page-link disabled" href="{% my_url person_page_obj.previous_page_number 'page' request.GET.urlencode %}">이전</a>
                    </li>
                {% else %}
                    <li class = "page-item disabled">
                        <a class = "page-link disabled" href = "#">이전</a>
                    </li>
                {% endif %}

                <li class = "page-item active">
                    <a class = "page-link" style="background: #e32879; border: none;">{{person_page_obj.number}}/{{person_page_obj.paginator.num_pages}}</a>
                </li>

                {% if person_page_obj.has_next %}
                    <li class = "page-item">
                        <a class = "page-link disabled" href="{% my_url person_page_obj.next_page_number 'page' request.GET.urlencode %}">다음</a>
                    </li>
                {% else %}
                    <li class = "page-item disabled">
                        <a class = "page-link disabled" href = "#">다음</a>
                    </li>
                {% endif %}
            </ul>
        </nav>
    </div>
</div>
</section>
{% else %}
<div class="box">
    <section class="logout-page">
            <h3>로그인 후 이용이 가능합니다.</h3>
            <div class="btn-area">
                <button onclick="location.href='{% url 'account_login' %}'">로그인</button>
                <button onclick="location.href='{% url 'account_signup' %}'">회원가입</button>
            </div>
    </section>
</div>
{% endif %}
</body>
<style>
.logout-page{
    font-family: 'Noto Sans JP', sans-serif;
    justify-content: center;
    align-items: center;
    margin-top: 15%;
}
.logout-page h3{
    font-size: 30px;
    margin-bottom: 50px;
    color: #fff;
    text-align: center;
}
.btn-area{
    text-align: center;
}
.btn-area button{
    background-color: #e32879;
    color: #FFF;
    font-size: 20px;
    border: none; 
    border-radius: 10px; 
    width: 200px;
    height: 50px;
}
.btn-area button a {
    color: #fff;
}
.search, .write {
    background-color: #e32879;
    color: #FFF;
    border: none; 
    border-radius: 3px; 
}
.write a {
    color: #fff;
}
th, td{
    color:#fff;
}
td a {
    color: #e32879;
}
.title a {
    color: #fff;
}
.title a:hover {
    color: #e32879;
}
</style>
{% endblock %}

weather_wear/community/templates/community/update_comment.html
{% extends 'base.html' %}
{% block content %}
<section class="services-section spad">
    <div class="row">
        <div class="col-lg-12">
            <div class="section-title" style="margin-bottom: 30px;">
                <h2>댓글 수정</h2>
            </div>
        </div>
    </div>
    <div class="container"> 
	    <form action="{% url 'community:update_comment' comment.id %}" method="POST"> 
		{% csrf_token %} 
		 <div class="form-group">
			 <label><p>댓글 내용</p></label>
			 <textarea class="form-control" name="content"> {{ comment.content }} </textarea><br>
             <button type="submit" value="댓글 수정">댓글 수정</button>
		 </div>
	 </form> 
</div>
<style>
    .form-group{
        text-align: center;
    }
    p{
        margin-bottom: 0px;
    }
    button{
        background: #e32879;
        border:none;
        color:#fff;
        border-radius: 10px;
    }
</style>
{% endblock %}